steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_URI}', '-f', 'ml/training/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_URI}']
images:
  - '${_IMAGE_URI}'